name: AI Resume Analyzer CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django
        
    - name: Run tests
      run: |
        cd backend
        pytest
        
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run tests
      run: |
        cd frontend
        npm test -- --passWithNoTests
        
  build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and tag backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: false
        tags: ai-resume-analyzer-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and tag frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: false
        tags: ai-resume-analyzer-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
  # Uncomment this job when you're ready to deploy
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Deploy to production
  #     run: echo "Add your deployment steps here"
